-- 코드를 입력하세요
#OUT 입양 보낸
#IN 보호 시작
SELECT outs.ANIMAL_ID, outs.ANIMAL_TYPE, outs.NAME
FROM ANIMAL_OUTS as outs JOIN ANIMAL_INS as ins
ON (
    outs.ANIMAL_ID = ins.ANIMAL_ID AND
    (outs.SEX_UPON_OUTCOME LIKE "Spayed%" OR outs.SEX_UPON_OUTCOME LIKE "Neutered%")  AND (ins.SEX_UPON_INTAKE LIKE "Intact%")
)
ORDER BY outs.ANIMAL_ID

 

# (SELECT ANIMAL_ID,ANIMAL_TYPE,NAME
# FROM ANIMAL_OUTS
# WHERE (SEX_UPON_OUTCOME LIKE "Spayed%" OR "Neutered%") AND NAME IS NOT NULL) 
# UNION
# (SELECT ANIMAL_ID,ANIMAL_TYPE,NAME
#       FROM ANIMAL_INS
#       WHERE (SEX_UPON_INTAKE LIKE "Intact%") AND NAME IS NOT NULL)
# #ON ANIMAL_OUTS.ANIMAL_ID =ANIMAL_INS.ANIMAL_ID
#       #정렬
# ORDER BY ANIMAL_ID